name: 'PackageMonster'
description: 'Checks if a NuGet package exists in the nuget.org public repository.'
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings
  color: purple
inputs:
  package-name:
    description: 'The name of the package.  This is not case-sensitive.'
    required: true
  version:
    description: 'The version of the NuGet package to check.  This is not case-sensitive.'
    required: true
  fail-when-not-found:
    description: 'If true, will fail the workflow if the NuGet package of the requested version does not exist.'
    required: false
    default: false

outputs:
  nuget-exists:
    description: 'True if the NuGet package exists.'

# These are the arguments that are passed into the console app
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--package-name'
  - ${{ inputs.package-name }}
  - '--version'
  - ${{ inputs.version }}
  - '--fail-when-not-found'
  - ${{ inputs.fail-when-not-found }}
