name: 'PackageMonster'
description: 'Checks if a package exists in the a public repository.'
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings
  color: purple
inputs:
  package-name:
    description: 'The name of the package.  This is not case-sensitive.'
    required: true
  version:
    description: 'The version of the package to check.  This is not case-sensitive.'
    required: true
  source:
    description: 'The source repository to check. The string `PACKAGE-NAME` will be replaced with the value from the `package-name` input parameter. Options: [ `nuget`, `npm`, custom url ]'
    required: false
    default: nuget
  json-path:
    description: 'The json path to extract the versions. Required only if a custom source url is specified.'
    required: false
  fail-when-not-found:
    description: 'If true, will fail the workflow if the package of the requested version does not exist.'
    required: false
    default: 'false'
  fail-when-found:
    description: 'If true, will fail the workflow if the package of the requested version does exist.'
    required: false
    default: 'false'

outputs:
  package-exists:
    description: 'True if the package exists.'

# These are the arguments that are passed into the console app
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--package-name'
  - ${{ inputs.package-name }}
  - '--version'
  - ${{ inputs.version }}
  - '--source'
  - ${{ inputs.source }}
  - '--json-path'
  - ${{ inputs.json-path }}
  - '--fail-when-not-found'
  - ${{ inputs.fail-when-not-found }}
  - '--fail-when-found'
  - ${{ inputs.fail-when-found }}
