name: ✅Build Status Check


env:
  PROJECT_NAME: PackageMonster
  NET_SDK_VERSION: 7.x


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches: master
    paths:
      - "**.cs"
      - "**.csproj"


jobs:
  build_status_check:
    name: Build Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get Build Config
      id: get-build-config
      run: |
        # If the destination branch that the pull request is merging into is master, do a release build
        if ( "${{ github.base_ref }}" -eq "master") {
          "build-config=Release" >> "$env:GITHUB_OUTPUT";
        } else { # Any other branch than master, do a debug build
          "build-config=Debug" >> "$env:GITHUB_OUTPUT";
        }

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_SDK_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore "${{ github.workspace }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"

    - name: Build Project
      run: dotnet build "${{ github.workspace }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" `
        -c ${{ steps.get-build-config.outputs.build-config }} `
        --no-restore
