name: ✅Build Status Check


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: main


jobs:
  build_status_check:
    name: Build Status Check
    uses: KinsonDigital/Infrastructure/.github/workflows/reusable/build-csharp-project.yml@v9.0.0
    with:
      project-name: "${{ vars.PROJECT_NAME }}"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
      base-path: "${{ github.workspace }}"
      runs-on: ubuntu-latest
